[tool.poetry]
name = "paibox"
version = "0.0.1"
description = "New toolbox of PAICORE 2.0."
authors = ["Ziru Pan <zrpan@stu.pku.edu.cn>"]
maintainers = ["Ziru Pan <zrpan@stu.pku.edu.cn>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/PAICookers/PAIBox"
homepage = "https://github.com/PAICookers/PAIBox"
documentation = "https://github.com/PAICookers/PAIBox#readme"
keywords = ["PAICORE 2.0", "PAIBox", "Toolbox"]
packages = [{ include = "paibox" }]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^2.0"
numpy = "^1.23.0"
torch = { version = "^2.1.0+cpu", optional = true, source = "torch-cpu" }
torchvision = { version = "^0.16.0+cpu", optional = true, source = "torch-cpu" }
torchaudio = { version = "^2.1.0+cpu", optional = true, source = "torch-cpu" }
paicorelib = "^0.0.7"


[tool.poetry.group.test.dependencies]
pytest = { version = "^7.4.0", python = "^3.8" }


[tool.poetry.group.dev.dependencies]
ujson = "^5.8.0"

[tool.poetry.extras]
torch_env = ["torch", "torchvision", "torchaudio"]

[tool.pytest.ini_options]
minversion = "7.0.0"
testpaths = ["tests"]


[[tool.poetry.source]]
name = "torch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"


[[tool.poetry.source]]
name = "PyPI"
priority = "primary"


[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
priority = "default"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
